// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type PlateObservation struct {
	ID          int64
	PlateNumber string
	Timestamp   int64
	Location    int64
	RoadID      int64
}

type Road struct {
	ID         int64
	SpeedLimit int64
}
